### ISSUE TITLE
Support multiple source folders

### ISSUE THREAD

**Issue by markspolakovs** [lablabs/prometheus-alert-overrider#4]
I'd like to be able to have two separate source folders for alerts, for example `base-rules/` and `custom-rules/`, to keep my overrides separate from the rules they override.

In the current implementation I don't think this is possible - alert-overrider only accepts one folder as an argument, and `ioutil.ReadDir` doesn't recurse.

I'd be happy to file a PR to add this.

**Comment by martinhaus** [comment]
Hey @markspolakovs!
If you are able to make a PR then I'm happy to review it and integrate this feature. I think it's a good idea.
